# Generated by Django 3.0.5 on 2020-05-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBVBlogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='Blogs',
        ),
    ]
